# Generated by Django 3.0.3 on 2020-02-06 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('about', models.TextField(max_length=300)),
                ('content', models.TextField(max_length=1024)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculties.Faculty')),
            ],
        ),
    ]
